### ISSUE TITLE
ev3 leds implementation

### ISSUE THREAD

**Issue by ddemidov** [rhempel/ev3dev-lang-python#13]
I am thinking of adding predefined instances for ev3 leds. Something along these lines [right after the usual `led` class declaration](https://github.com/rhempel/ev3dev-lang-python/blob/a906045c79153dae9331ec78be4017d017a39d25/ev3dev.py#L1501):

```py
led.red_left    = led(name='ev3-left0:red:ev3dev')
led.red_right   = led(name='ev3-right0:red:ev3dev')
led.green_left  = led(name='ev3-left1:green:ev3dev')
led.green_right = led(name='ev3-right1:green:ev3dev')
```

I think though @rhempel would suggest that we put the names into `autogen/spec.json` and use it to generate the above code. Hence the question: we in principle should support both EV3 and RPI, and I guess RPI features different set of leds. How do we deal with this in specification?

**Comment by rhempel** [comment]
You are correct - and now that I think about it, when we get more platforms running ev3dev they will likely have their own drivers for motors and sensors because the underlying hardware may be different. Would we have a separate `spec.json` for those platforms - maybe `spec-ev3.json` and `spec-rpi.json` and `spec-bb` (for BeagleBone) ?

**Comment by ddemidov** [comment]
I think that is a nice idea. We could have the main `spec.json` that should be universal, and a spec per platform that would describe the platform-specific features. But since that would involve changes in autogen, we should probably open an issue in the main repo.
