### ISSUE TITLE
Python IDEs for ev3dev that can run on Lego brick

### ISSUE THREAD

**Issue by edmundronald** [rhempel/ev3dev-lang-python#160]
This thread is for discussing IDEs, preferably with code completion, etc. that will facilitate ev3dev application work.

Ideally, an IDE would be able to facilitate writing code by showing the package function definitions or documentation links. And it makes sense to talk about this as a design criterion for the code itself. 

@nadehi18 has suggested atom.

Edmund

**Comment by nadehi18** [comment]
Atom is good if you are on a unix based system, as I don't think installing
rsync is easy on windows although I may be wrong.  Another to check out
would be sublime text maybe, although I haven't used it personally.

**Comment by edmundronald** [comment]
I would prefer to have something that runs on the EV3, because that way I can log in from anything that is lying around, including my iPad, and the files are already where I want them. 
Also, the IDE might as well be in the EV3 release.

Edmund

**Comment by nadehi18** [comment]
Hmm, I think I saw a while ago about a web based IDE called ipython or
python notebook that allowed u to run things on it, basically anything for
the raspberry pi would work.

**Comment by edmundronald** [comment]
Yup iPython or Jupyter allow one to create notebooks, but they're not really IDEs. I guess we'll continue this discussion when I have my brick with me again - at the moment I'm on vacation. Thank you pfor suggesting atom and sublime text!

**Comment by WasabiFan** [comment]
@nadehi18 Yes, there has been some previous discussion surrounding that project on ev3dev. In general, the conclusion has been that any editor running on the EV3 in real time is too slow for normal use (see ev3dev/ev3dev#432) because the processor isn't able to keep up with the work of hosting the live session.

There is [one tutorial](http://www.ev3dev.org/docs/tutorials/setting-up-python-pycharm/) on ev3dev.org already that explains how to get PyCharm running. I haven't tried it myself, but as far as I know it should do what you are looking for, so I'd suggest trying that out. Note that there has been some discussion on this in ev3dev/ev3dev#619. Someone was having trouble following that tutorial, so if you try out this option it would be helpful if you post back there with your findings.

If you aren't happy with that option, I would recommend using your own editor that copies files over the network when you save. This minimizes the amount of work that the EV3 has to do and gives you a native experience with a choice of IDEs. This is how I do my ev3dev development; I use Visual Studio Code along with a community-made file sync plugin and I have found that it does everything that I need without any lag.  Alternatively, if you don't have an editor with sync functionality, you could also try [setting up an NFS file share](http://www.ev3dev.org/docs/tutorials/setting-up-an-nfs-file-share/) or using a tool such as WinSCP or FileZilla to do the copy manually (but still quickly).

There has been a large amount of discussion on this topic in ev3dev/ev3dev#477, so I would recommend skimming through there to see if there's anything of interest to you. And it would be great to hear your opinion on what we can do to make the "getting started workflow" better (which is what we have been discussing there)!

**Comment by edmundronald** [comment]
@WasabiFan Dev envs are a recurring issue with the new linux-based devices which are not really embedded one-trick poneys, and not really full servers. I had much of the same issue with my Arduino Yun, which runs OpenWRT.

I'll scan through the refs you provided. 

In the mean time, thank you for providing a beginner-friendly environment! 

Edmund

**Comment by nadehi18** [comment]
I did think about that afterward, seeing as a board like the raspberry pi
has like 1GB of ram and a 1 or more Ghz processor where as the ev3 only has
64mb of ram and a 300 MHz processor, although I did notice that there is
swap space on ev3dev so that night help somewhat but swap is usually slow.
I do the same as you except with atom, and it's a very nice workflow
because you can write something it syncs and pop over to your terminal and
run the program, I'm sure there's even plugins that would let you have a
terminal in your IDE probs.
@wasabifan

**Comment by edmundronald** [comment]
I am looking through this https://wiki.python.org/moin/IntegratedDevelopmentEnvironments

Obviously, anything running X is going to be out.

**Comment by laurensvalk** [comment]
I'm presently using this, which is very light and easy to use:

![geany2](https://cloud.githubusercontent.com/assets/12326241/15074047/1cf45e84-139d-11e6-909b-6136b0751244.png)

In Ubuntu, it's very easy to just open the files on the EV3 by clicking "connect to server" in the file browser. 

Then, you can just edit your code in any text editor you like. When you save your code, it's immediately stored on the EV3.

I use Geany, because it has a built-in terminal, but you could use something else and have a separate terminal window.

**Comment by nadehi18** [comment]
Ah, nice, I never thought of connecting to it using nautilus, but I still
like having a local copy of the programs as well.

**Comment by laurensvalk** [comment]
You could copy paste it to a local folder after you're done, or even use something to sync it to a local folder automatically after each save, or use github.

**Comment by edmundronald** [comment]
Laurens, I think the "good" Python IDEs can do code completion, retrieve docs etc from any module ...but maybe for that they need to be running Python on the target. I'm talking from the perspective of a "beginner" who doesn't know where the docs are etc for the functionality - ie how to run a motor.

The big advantage of the Lego iconic language is that it is self-disclosing and self-documenting. Each tile tells you what you can do with that component.

**Comment by laurensvalk** [comment]
I'm aware, there have been quite a few threads about this. It's getting better. Ev3dev is just not there yet at this time.

**Comment by edmundronald** [comment]
I like a lot; And I'm saying there might be some Python introspection technology out there we might leverage to make it even better easily, just like your mounting trick solves the Edit issue on Linux, and probably on Mac too with eg. TextWrangler.

**Comment by nadehi18** [comment]
I'm on mobile atm, so when I get on my computer I'll give you a link to the
python ev3dev docs, they can be hard to understand, but I've already used
python so it's simple after you figure out what each variable and function
actually does, I'll also tell you now that for motors, duty_cycle_sp is the
speed variable for some reason?

**Comment by edmundronald** [comment]
@nadehi18 thx i am on mobile too. i will come back to you for help!
Atm we're discussing finding a way for an sdk to *automagically* bring up the docs etc while the enduser  editing ev3dev app code.

**Comment by edmundronald** [comment]
@laurensvalk btw what did you improve in the balanc3r code? it is really much better. Have you found a better way to filter the gyro?

**Comment by nadehi18** [comment]
I guess the first question would be whether or not the ev3dev module keeps
local versions of its docs (if assume yes but I'm not sure) and then I
believe there's a command that will show the documentation for something on
python…

**Comment by laurensvalk** [comment]
> btw what did you improve in the balanc3r code? it is really much better. Have you found a better way to filter the gyro?

I'm not sure what you mean as I didn't make changes recently, but you are welcome to ask about the segway code on its Github page [here] (https://github.com/laurensvalk/segway/issues). I'm certainly interested in hearing about the code apparently performing differently.

**Comment by edmundronald** [comment]
I've posted a query on the atom forum; I think there should be a way to do introspection on the brick (or any remote machine) by editing the "run python" command preferences or something in the editor. 

https://discuss.atom.io/t/edit-locally-code-complete-on-remote-python-mindstorms-ev3dev/28592

**Comment by edmundronald** [comment]
I have been playing around with various IDEs on the brick. 

Console-mode emacs is very good, syntax coloration etc, and fast,  with Terminal.app on the Mac supplying the console, any font you want. Of course you need to be happy to deal with emacs. 
The install line is given below, and one needs to know that F10 invokes the menu.

```sudo apt-get install emacs24-nox
```

If one is willing to run X on the computer side, then Idle is usable, and also Geany. I tried them with Bluetooth and tethering, bluetooth is bad, tethering gives -barely- tolerable speed. The trick to getting an X server on a comp to work with clients on the brick is to install Xauth.  **I believe Xauth should be installed by default together with some simple X clients eg. xclock to allow people to test their X configuration quickly.**

**Comment by edmundronald** [comment]
I closed this issue by mistake - my bad. Apologies.

**Comment by nadehi18** [comment]
Bluetooth works fine for me, but I don't use tethering, I just followed the
tutorial for Bluetooth on Ubuntu 14.04 on the ev3dev website using blueman.

**Comment by edmundronald** [comment]
Yes. Bluetooth works fine with Emacs, it is too slow for heavy X graphics apparently. Wired works -barely.  Maybe wifi will work better.

**Comment by psychemedia** [comment]
Another approach to running a GUI is to have a GUI client on a host and connect it to use a remote IPython kernel on the EV3.

If you have a client that works with Jupyter, a Jupyter server on a host can connect to a remote IPython kernel on the EV3.

See also this thread: https://github.com/ev3dev/ev3dev/issues/630#issuecomment-218870494

**Comment by psychemedia** [comment]
On the IPython front (IPython kernel running on brick and connecting to that as a remote kernel from elsewhere), I wonder if the [Atom Hydrogen extension](https://atom.io/packages/hydrogen) lets you work with remote kernels?

**Comment by dwalton76** [comment]
Will close this one since I don't think there are any changes to make to the repo and the discussion had died down. Feel free to re-open if needed.
