### ISSUE TITLE
Fix recommendation in README to upgrade using easy_install

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#199]
I could be wrong, but I think that the recommendation to use `easy_install` to upgrade the installed version of the package for Python 3 compatibility is not what we want to be there. By default, the `python-ev3dev` Debian package is installed (currently version 0.6.0). Instead of installing the module again using `easy_install`, shouldn't the README suggest installing the `python3-ev3dev` package and using that instead?

**Comment by dwalton76** [comment]
I tend to agree...push them towards 'sudo apt-get update && sudo apt-get upgrade' instead.  The exception would be if you've git cloned this repo and want to do dev against it and need to install the latest code from the repo.  That would probably be worth putting in a dev-HOWTO document instead of the README though.

**Comment by WasabiFan** [comment]
I think this has been resolved by the README changes; any objections to closing this?

**Comment by dwalton76** [comment]
None here
