### ISSUE TITLE
I can not  run my Python script from within Brickman

### ISSUE THREAD

**Issue by DJuego** [rhempel/ev3dev-lang-python#245]
Yes. I have tested succesfully two python script in the command line.

I have made the scripts executable ( In fact i see an asterisk (*) displayed after their file names)
I have added the line #!/usr/bin/env python3 to the top of my programs.

Result:
The lcd is cleared...  The leds turn on orange...  a few seconds... and the ev3dev interface returns without errors and the leds turn on green. Actually, i have two scripts (server and client) and two EV3 bricks in a Wifi network. The scripts work when they are launched from the command line.  Any idea? I have "print" lines (code for console). Is that a problem? 

DJuego

**Comment by WasabiFan** [comment]
Interesting. Can you provide a minimal example script that exhibits this behavior?

My guess is that your script is throwing an error, and the error is flashing on the screen rapidly before Brickman loads again. One debugging option here is that you could write a simple bash script that invokes your script and pipes any errors to a file, then you could run that script from Brickman to see if it saves anything of use.

There have been hopes of improving Brickman so that it logs errors that occur in user programs, but that hasn't been implemented yet. @dlech do you have any other ideas?

**Comment by dlech** [comment]
Windows line endings.

**Comment by WasabiFan** [comment]
Ah, good point! One likely cause of this issue is using Windows editors to write your code. Windows traditionally inserts invisible characters at the end of each line which Linux-based systems to not expect. In your editor, check to see if there's a "line endings" option, and if there is one change it to "Unix-style".

**Comment by DJuego** [comment]
That's the problem! It works perfectly!👍  I am sure that I would never have it discovered!. Thanks **@dlech** (again) and thank you **@WasabiFan** too. Is this in the docs? I did not read it...

PS:
I had to have exposed it in my issue. Sorry! 👎 My environment is Windows 10 x64. I am using Spyder editor from Winpython. I am working with the shiny ev3dev-lang-python 0.8.0- Thanks for this. (Really I am a C/C++ guy. So I am very interested in the ev3dev-lang-cpp too however ev3dev-lang-python has interesting advantages. I have to admit it. )

**Comment by ddemidov** [comment]
> Is this in the docs?

Looks like its not. And this is not the first such issue we got, so it could be a good idea to add it to the README. @DJuego, would you like to do this?

**Comment by DJuego** [comment]
I thank you for your trust in me, **ddemidov**,  but i must decline. Mi English is poor. I prefer  documentation updated by individuals with a solid grasp of the language, (for the sake of community :-))

**Comment by WasabiFan** [comment]
No worries! Give me a bit and I'll write up a page. I'm thinking I'll add a FAQ page to the docs; @ddemidov does that sound good? I'll probably have a PR open before you wake up anyway, so we can discuss there :laughing:

**Comment by WasabiFan** [comment]
Wow, it took me 5 hours of (distractible) writing to accomplish this basic task.

**Comment by ddemidov** [comment]
"How I learned to stop worrying and love the RST"
