### ISSUE TITLE
kernel 18-ev3dev breaks EV3 buttons

### ISSUE THREAD

**Issue by dlech** [rhempel/ev3dev-lang-python#286]
In the 18-ev3dev kernel release, we fixed a long standing bug with the EV3 buttons. 1 for pressed and 0 for released were reversed. This most likely breaks some of the button code. You probably need to remove the `not` [here](https://github.com/rhempel/ev3dev-lang-python/blob/4a85fd2553e31ef723b478c101bd3c5cba84468f/ev3dev/core.py#L2558). Not sure if other changes need to be made, so please test.

**Comment by DJuego** [comment]
ensonic suspect that this [problem](https://github.com/OpenRoberta/robertalab-ev3dev/issues/32) is related with this issue (at least, partially)

**Comment by ensonic** [comment]
I changed /usr/lib/python3/dist-packages/ev3dev/core.py on the ev3 and can confirm that this fix works. I is super important to include this in a release before releasing a new image, since the openroberta lab has a restart key handler that can be used to reset a stuck program and due to the inverted logic, this triggers everytime now.
