### ISSUE TITLE
Additional language support in ev3dev python

### ISSUE THREAD

**Issue by wliu2016** [rhempel/ev3dev-lang-python#312]
To whom it may concern,

Thank you for your hard working in ev3dev project.  This is really amazing.  

I use Python 3 to program EV3.  Though it is convenient enough for me with English system, I am wondering if there is a way to make the system working in other language, such as Chinese.  Any help or comments will be appreciated.  

Thanks.  Have a good one.

Best,
Wenlong Liu

**Comment by WasabiFan** [comment]
Hmmm... interesting question. Are you looking for system localization (i.e., have Brickman and/or terminal commands display text in Chinese) or have Python functions be written in Chinese?

The difficulty with maintaining translations so that programs like Brickman can display in other languages is that every translation must be updated for each release... that makes it tough to make a small change and publish an update.

If you're looking for functions and variables to be in other languages, that's much more difficult. For a start, Python doesn't allow foreign characters in identifiers (the only language that I know of which does something like that is perl :wink:). For reasons primarily of consistency, the convention is generally to name things in English across most of the computer engineering field.

**Comment by wliu2016** [comment]
Thanks for reply.  I think I am looking for system localization.  It would be amazing to make Lego read, listen and speak Chinese, because most of my family and friends do not speak English.  Actually I don't mind working in English environment, just want to Lego EV3 to recognize Chinese characters. 

I googled a little bit regarding this issue.  I am trying to add Chinese language support in Lego EV3 and figure out if the system can recognize Chinese.  

For programming in Python, I think English is good enough.  If someone really wants to learn programming, language is not a huge difficulty. 

Thanks again for the comments.  Will update if I have some interesting findings.

**Comment by WasabiFan** [comment]
Ah, I get it. There are existing ways that you can configure the system to use other languages, but that setting only applies to apps that support it, which is rare; you probably wouldn't notice much of a difference. @dlech is the one who would know more.

**Comment by dlech** [comment]
I am working on better font support in GRX so this may be a possibility in the future. For command line applications `sudo dpkg-reconfigure locales` can be used to add more locales.

**Comment by ensonic** [comment]
+1 for localized brickman. Happy to do the german po file.

**Comment by WasabiFan** [comment]
I'm going to close this as it likely won't have an effect on the Python libraries. Down the road, the ev3dev platform as a whole might gain translation ability in which case there could be some reaction work to handle new fonts, but right now it's not a feature request for ev3dev-lang-python.
