### ISSUE TITLE
Unused files?

### ISSUE THREAD

**Issue by WasabiFan** [rhempel/ev3dev-lang-python#344]
I just noticed that there are two files which don't seem to be referenced anywhere. [`framebuffer.py`](https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/framebuffer.py) and [`virtualterminal.py`](https://github.com/rhempel/ev3dev-lang-python/blob/develop/ev3dev/virtualterminal.py), the two files in question, were both created in 2016 but it seems that we've since reimplemented the functionality (for the framebuffer, at least) in `core.py`. Are these files still needed/used?

**Comment by ddemidov** [comment]
> Are these files still needed/used?

Does not look like it. Quick grep does not show anything using these.

**Comment by WasabiFan** [comment]
While we're at it, what's `GyroBalancer.py`? @dwalton76? I'm moderately confused as to why it's in the `ev3dev` directory as opposed to `demos`.

**Comment by dwalton76** [comment]
GyroBalancer.py contains a base class for robots that stand on two wheels and use a gyro to keep their balance.  We put it in its own file instead of helper.py because
- it was a decent amount of code and felt cleaner to have it separate
- it is a port of Lauren's code and we wanted to keep his license at the top but that license didn't apply to everything else in helper.py

BALANC3R in the demo directory uses the GyroBalancer class

**Comment by dwalton76** [comment]
I don't know of any uses for framebuffer.py and virtualterminal.py
